# Generated by Django 5.0.6 on 2024-06-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('telephone', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
                'db_table': 'Contact',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
        migrations.AlterModelTable(
            name='store',
            table='Store',
        ),
    ]
