# Generated by Django 5.0.6 on 2024-07-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_contact_alter_news_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
